# Generated by Django 2.0.5 on 2018-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.CharField(max_length=50, unique=True)),
                ('Product_Name', models.CharField(max_length=150)),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
    ]
