# Generated by Django 2.0.5 on 2018-05-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('cat_id', models.CharField(max_length=2)),
            ],
        ),
    ]
