# Generated by Django 2.0.5 on 2018-05-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter1', '0002_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat',
            name='p_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
