# Generated by Django 2.0.5 on 2018-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter1', '0004_subsubcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='cat',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
