# Generated by Django 2.0.5 on 2018-05-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter1', '0005_data_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='cat',
        ),
    ]
